[package]
name = "marveledata"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
binrw = "0.13"
bytes = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
encoding_rs = "0.8"
