[package]
name = "anmchr-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
marveledata = { path = "../../marveledata" }
serde_json = "1"
tempfile = "3"
