use std::fs;
use std::io::Write;

use marveledata::{load_first, save_first};
use tempfile::NamedTempFile;

fn sample_bytes() -> Vec<u8> {
    include_str!("data/sample_first.hex")
        .split_whitespace()
        .map(|byte| u8::from_str_radix(byte, 16).expect("valid hex byte"))
        .collect()
}

#[test]
fn sample_file_is_non_empty() {
    let bytes = sample_bytes();
    assert!(!bytes.is_empty(), "sample fixture must not be empty");
}

#[test]
fn table_round_trip_preserves_bytes() {
    let bytes = sample_bytes();

    let mut input = NamedTempFile::new().expect("create temp input file");
    input
        .write_all(&bytes)
        .expect("write fixture bytes to temp file");
    input.flush().expect("flush temp input file");

    let model = load_first(input.path()).expect("parser should succeed");

    let output = NamedTempFile::new().expect("create temp output file");
    save_first(output.path(), &model).expect("writer should succeed");

    let regenerated = fs::read(output.path()).expect("read regenerated bytes");
    assert_eq!(bytes, regenerated, "round trip must match byte-for-byte");
}
