name: Rust CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libclang-dev
        continue-on-error: true
      - name: Cargo fmt
        run: cargo fmt --check
      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features
      - name: Cargo test
        run: cargo test --all
